export const TYPES = {
  GREETER: Symbol('GREETER'),
  PERSONAL_ASSISTANT: Symbol('PERSONAL_ASSISTANT'),
  MULTILINGUAL_GREETER: Symbol('MULTILINGUAL_GREETER'),
  SPANISH_GREETER: Symbol('SPANISH_GREETER'),
  ENGLISH_GREETER: Symbol('ENGLISH_GREETER'),
}
